version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: fsw-donalds-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
